AutomatedVerbalAutopsy/AutomatedVerbalAutopsy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('member.urls')),
    path('questionnaire/', include('questionnaire.urls')),
    path('prediction/', include('prediction.urls')),
    path('admin/', admin.site.urls),
]

AutomatedVerbalAutopsy/member/urls.py
from. views import LoginView,LogoutView,RegisterView
from django.urls import path
from .views import changePassword,forgetPassword,password_reset_view
from django.views.decorators.csrf import csrf_exempt

app_name = 'member'

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('register/<str:message>/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('forget_password/', password_reset_view, name='forget_password'),
    path('change_password/<token>/', changePassword, name='change-password'),
]

AutomatedVerbalAutopsy/prediction/urls.py
from django.urls import path
from . import views

app_name = 'prediction'

urlpatterns = [
    path('predict/', views.predict_disease, name='predict'),
    path('success/', views.success, name='success'),
    path('badili/', views.delete_questionnaire, name='badili'),
    path('download/<int:marehemu_id>/', views.download_report, name='download_report'),
    path('report/', views.report, name='report'),    
]

AutomatedVerbalAutopsy/questionnaire/urls.py
from django.urls import path
from. import views 
from django.contrib import messages
from django.views.defaults import permission_denied


handler403 = 'questionnaire.views.permission_denied_view'



app_name = 'questionnaire'

urlpatterns = [
     path('submit-form/', views.cod, name='submit_form'),
     path('submit-form/<str:message>/', views.cod, name='submit_form'),
     path('dashboard/', views.dashboard, name='dashboard'),
     path('profile/', views.profile, name='profile'),
     path('Updated-profile/', views.Updated_profile, name='Updated_profile'),
     path('update-profile/', views.updateProfile, name='update_profile'),
     path('change-password/', views.change_password, name='change_password'),
     path('password/', views.password, name='password'),
     path('ondoa_sababu/<int:marehemu_id>/', views.ondoa, name='ondoa_sababu'),
     path('badili_sababu/<int:marehemu_id>/', views.badili_sababu, name='badili_sababu'),
     # path('search/', views.search_marehemu, name='search_marehemu'),
]

AutomatedVerbalAutopsy/questionnaire/models.py
from django.db import models
from django.utils import timezone




class Shuhuda(models.Model):
    Uhusiano_marehemu = (
        ('Baba', 'Baba'),
        ('Mama', 'Mama'),
        ('ndugu', 'ndugu'),
        ('Hakuna Uhusiano', 'Hakuna Uhusiano'),
        ('Nyingine','nyingine')
    )
    Uhusiano_kifo=(
        ('Ndio','Ndio'),
        ('Hapana','Hapana'),
    )
    first_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    place = models.CharField(max_length=255)
    region = models.CharField(max_length=255)
    simu = models.CharField(max_length=100, default='')
    uhusiano = models.CharField(max_length=255, choices=Uhusiano_marehemu)
    uhusiano_kipindi_kifo = models.CharField(max_length=255, choices=Uhusiano_kifo)

    def __str__(self):
        return self.first_name


class Marehemu(models.Model):
    shuhuda=models.ManyToManyField(Shuhuda, verbose_name=("Shhuda_Wa_Kifo"))
    Ndoa = (
        ('ndoa', 'ndoa'),
        ('hajafunga ndoa', 'hajafunga ndoa'),
        ('mjane', 'mjane'),
        ('mgane', 'mgane'),
        ('talaka','talaka'),
        ('kutengana','kutengana')
    )
    Mahali = (
        ('nyumbani', 'nyumbani'),
        ('hospitali', 'hospitali'),
        ('kituo cha afya', 'kituo cha afya'),
        ('sijui', 'sijui')
    )
    Jinsia=(
        ('mume','mwanaume'),
        ('mke','mwanamke')
    )
    jina_kwanza = models.CharField(max_length=255 )
    jina_pili = models.CharField(max_length=255)
    jina_mwisho = models.CharField(max_length=255)
    jinsia = models.CharField(max_length=255, choices=Jinsia)
    ndoa = models.CharField(max_length=255, choices=Ndoa)
    kuzaliwa = models.DateField(default=timezone.now)
    kufa = models.DateField(default=timezone.now)
    mahali = models.CharField(max_length=255, choices=Mahali)
    maelezo = models.TextField()
 
    def __str__(self):
       return self.jina_kwanza


    
class Sababu(models.Model):
    Marehemu=models.OneToOneField(Marehemu, verbose_name=("Sababu_Ya_Kifo"), on_delete=models.CASCADE)
    sababu = models.CharField(max_length=255)

    def __str__(self):
       return self.sababu

AutomatedVerbalAutopsy/questionnaire/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View
from django.contrib import messages
from django.contrib import auth
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth import update_session_auth_hash
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Shuhuda,Marehemu,Sababu
from django.shortcuts import render, redirect, get_object_or_404
import plotly.graph_objects as go
from django.db.models import Count
from django.contrib.auth.decorators import user_passes_test

def group_check(user):
    return user.groups.filter(name='interviewer').exists()

def permission_denied_view(request, exception):
    return render(request, 'questionnaire/permission_denied.html', status=403)



@login_required
def cod(request, message=None):
    email=request.user.email
    username = request.user.username  # Get the authenticated user's username
    if request.method == 'POST':
            formShuhuda = Shuhuda(
                first_name=request.POST['firstName'],   
                middle_name=request.POST['middleName'],  
                last_name=request.POST['lastName'],  
                place=request.POST['place'],
                region=request.POST['region'],
                simu=request.POST['simu'],
                uhusiano=request.POST['uhusiano'],
                uhusiano_kipindi_kifo=request.POST['uhusiano_kipindi_kifo'],
            )

            formMarehemu= Marehemu(
                jina_kwanza=request.POST['jina_kwanza'],
                jina_pili=request.POST['jina_pili'],
                jina_mwisho=request.POST['jina_mwisho'],
                jinsia=request.POST['jinsia'],
                ndoa=request.POST['ndoa'],
                kuzaliwa=request.POST['kuzaliwa'],  
                kufa=request.POST['kufa'], 
                mahali=request.POST['mahali'],
                maelezo=request.POST['maelezo']
            )
            formShuhuda.save()
            formMarehemu.save()
            

            return redirect('prediction:predict')
    
    return render(request, 'questionnaire/form.html', {'username': username, 'message': message})


@login_required
def dashboard(request):
    username = request.user.username 
    sababu_values = Sababu.objects.all().order_by('-id')
    marehemu_values = Marehemu.objects.select_related('sababu').prefetch_related('shuhuda').order_by('-id')
    search_query = request.GET.get('query')
    if search_query:
      marehemu_values = marehemu_values.filter(jina_kwanza__icontains=search_query)

    paginator = Paginator(marehemu_values, 10) 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    sababu_counts = Sababu.objects.annotate(count=Count('sababu'))
    labels = [sababu.sababu for sababu in sababu_counts]
    values = [sababu.count for sababu in sababu_counts]
    plot_data = {'labels': labels, 'values': values}

    combined_data = {
        'sababu_values': sababu_values,
        'marehemu_values': page_obj,  
        'plot_data':plot_data,
        'username':username
    }
    return render(request, 'questionnaire/dashboard.html', {'combined_data': combined_data})

@user_passes_test(lambda user: user.groups.filter(name='physician').exists(), login_url='permission_denied')
def ondoa(request, marehemu_id):
    marehemu = get_object_or_404(Marehemu, id=marehemu_id)
    sababu_to_delete = marehemu.sababu
    marehemu_to_delete=marehemu
    if request.method == 'POST':
        sababu_to_delete.delete()
        marehemu_to_delete.delete()
        
        return redirect('questionnaire:dashboard')
    context = {
        'object_to_delete': marehemu_to_delete,
        'sababu_to_delete':sababu_to_delete,
    }
    return render(request, 'questionnaire/delete.html', context)

@user_passes_test(lambda user: user.groups.filter(name='physician').exists(), login_url='permission_denied')
def badili_sababu(request, marehemu_id):
    marehemu = get_object_or_404(Marehemu, id=marehemu_id)
    sababu_to_modify = marehemu.sababu
    if request.method == 'POST':
        new_sababu = request.POST.get('new_sababu')
        sababu_to_modify.sababu = new_sababu
        sababu_to_modify.save()
        return redirect('questionnaire:dashboard')
    context = {
        'object_to_modify': sababu_to_modify,
    }
    return render(request, 'questionnaire/edit.html', context)


  
@login_required
def profile(request,message=None):
     username = request.user.username 
     email=request.user.email
     first_name =request.user.first_name
     last_name = request.user.last_name
     return render(request, 'questionnaire/profile.html',{'username': username, 'message': message, 'email':email,'first_name':first_name,'last_name':last_name})


@login_required
def change_password(request):
    username = request.user.username 
    email=request.user.email
    if request.method == 'POST':
        current_password = request.POST['currentPassword']
        new_password = request.POST['newPassword']
        confirm_password = request.POST['confirmPassword']
        if request.user.check_password(current_password):
            if new_password == confirm_password:
                request.user.set_password(new_password)
                request.user.save()
                update_session_auth_hash(request, request.user) 
                messages.success(request, 'Password changed successfully.')
            else:
                messages.error(request, 'New password and confirmation password do not match.')
        else:
            messages.error(request, 'Incorrect current password.')

    return redirect('/questionnaire/profile')  


def password(request):
    username = request.user.username
    first_name =request.user.first_name
    last_name = request.user.last_name 
    return render(request, 'questionnaire/change_password.html')

def updateProfile(request,message=None):
    username = request.user.username 
    return render(request, 'questionnaire/update_profile.html')

def Updated_profile(request, message=None):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        user = request.user
        user.username = username
        user.email = email
        user.save()
        messages.success(request, 'Your profile has been updated successfully.')
        return redirect('questionnaire:profile')
    else:
        username = request.user.username
        email = request.user.email
        return render(request, 'questionnaire/profile.html', {'username': username, 'message': message,
                                                              'email': email })

AutomatedVerbalAutopsy/questionnaire/templates/questionnaire/change_password.html
{% extends 'questionnaire/main.html'%}

{% block content%}
<div class="container mt-5 border border-solid p-4">
<form id="changePasswordForm" action="{% url 'questionnaire:change_password' %}" method="post">
    {% csrf_token %}
    <div class="text-center mb-1">
        <h2>Change Password</h2>
      </div>
    <div class="form-group">
      <label for="currentPassword"> Password</label>
      <input type="password" class="form-control" id="currentPassword" name="currentPassword" required>
    </div>
    <div class="form-group">
      <label for="newPassword">New Password</label>
      <input type="password" class="form-control" id="newPassword" name="newPassword" required>
    </div>
    <div class="form-group">
      <label for="confirmPassword">Comfirm Password</label>
      <input type="password" class="form-control" id="confirmPassword" name="confirmPassword" required>
    </div>
    <button type="submit" class="btn btn-primary">Save </button>
  </form>
</div>
{% endblock%} 

AutomatedVerbalAutopsy/questionnaire/templates/questionnaire/dashboard.html
{% extends 'questionnaire/main.html'%}
{% load static %}

{% block content%}
{% if user.is_authenticated  %}
 <div class="row mt-5">
  <div class="row">
    <div class="col-md-2">
      <button id="add-form-btn" id="add-form-btn"  class="btn btn-secondary p-2">+ Ongeza Fomu</button>
    </div>
     <script>
      document.getElementById('add-form-btn').addEventListener('click', function() {
        window.location.href = '/questionnaire/submit-form/';
      });
    </script>
    <div class="col-md-6"></div>
    <div class="col-md-4">
      <form id="search-form" class="form-inline">
        <div class="form-group">
          <input type="text" id="search-results" class="form-control" placeholder="Tafuta..." onsubmit="searchData(event)">
        </div>
      </form>
    </div>
  </div>

  <div class="row mt-4">
    <div class="col-md-12">
      <table id="marehemu-table" class="table table-hover">
        <thead>
          <tr>
            <th>Jina Kamili</th>
            <th>Mahali</th>
            <th>Maelezo</th>
            <th>Sababu</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
          <tbody>
            {% for marehemu in combined_data.marehemu_values %}
            <tr>
                <td>{{ marehemu.jina_kwanza }} {{ marehemu.jina_pili }} {{ marehemu.jina_mwisho }}</td>
                <td>{{ marehemu.mahali }}</td>
                <td>{{ marehemu.maelezo }}</td>
                <td>
                    {{ marehemu.sababu.sababu }}
                </td>
                <td><a href="{% url 'questionnaire:badili_sababu' marehemu.id %}"  class="btn btn-secondary text-light">Badili</a></td>
                <td><a href="{% url 'questionnaire:ondoa_sababu' marehemu.id %}"  class="btn btn-danger text-light">Ondoa</a></td>
            </tr>
            {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% comment %} <script src="{% static 'javascript/search.js' %}"></script> {% endcomment %}
<script src="{static 'javascript/search.js'}"></script>
{% endif %}
{% endblock %}

AutomatedVerbalAutopsy/questionnaire/templates/questionnaire/delete.html
{% extends 'questionnaire/main.html'%}

{% block content %}
  <h1>Delete Confirmation</h1>
  <p>Are you sure you want to delete {{ object_to_delete }}?</p>
  
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
    <a href="{% url 'questionnaire:dashboard' %}">Cancel</a>
  </form>
{% endblock %}

AutomatedVerbalAutopsy/questionnaire/templates/questionnaire/edit.html
{% extends 'questionnaire/main.html'%}

{% block content %}
  <h1>Badili Sababu</h1>
  <form method="POST" >
    {% csrf_token %}
    <div class="form-group">
      <label for="new_sababu"> Sababu Mpya:</label>
      <input type="text" name="new_sababu" class="form-control" id="new_sababu" value="{{ object_to_modify.sababu }}">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
{% endblock %}

AutomatedVerbalAutopsy/questionnaire/templates/questionnaire/main.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <title>CODM</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">

    

    <!-- Bootstrap core CSS -->
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'questionnaire/css/boostrap_min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


    {% load static %}
    <!-- Favicons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.css">
<script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


     {% load static %}
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

     <link rel="stylesheet" href="{% static 'questionnaire/css/style.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'popup.css' %}">

  

    
    <!-- Custom styles for this template -->
    {% load static %}
<link rel="stylesheet" href="{% static 'questionnaire/css/main.css' %}">


  </head>
  <body>
    
<header class="navbar navbar-success sticky-top flex-md-nowrap p-0 shadow back p-2">
    <div class="container-fluid">
        <a class="nav-link text-light px-3 fs-5" href="#">CAUSES OF DEATH DETERMINATION</a>
    </div>
    <div class="btn-group bg-light mr-3">
      <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        <span class="fa fa-user  ">&nbsp;<i class="caret"></i></span>
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <ul class="dropdown-menu" role="menu" style="right: 0; left: auto;">
        <!-- Dropdown menu items -->
        <li>
          {% if username %}
          <a class="dropdown-item" > {{ username }}</a>
          
        </li>
          {% endif %}
        <li><hr class="dropdown-divider"></li>
        <li>
          <a class="dropdown-item" href="{% url 'questionnaire:profile' %}">View Profile</a>
        </li>
        <li><a class="dropdown-item" href="{% url 'questionnaire:password' %}">Change Password</a></li>
        <li><a  class="dropdown-item " href="{% url 'member:logout' %}">Logout</a>
       </li>
      </ul>
    </div>
</header>

<div class="container-fluid">
  <div class="row ">
    {% load static %}
   
  </div>
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <div class="m-3 mb-5">
        <img src="{% static 'questionnaire/images/logo.png' %}" alt="Logo" style="width:150px; height:150px;">
      </div>
      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4  mx-2 mb-1 text-muted">
        <span>Kuhusu Mahojiano</span>
        <a class="link-secondary" href="#" aria-label="Add a new report">
          <span data-feather="plus-circle"></span>
        </a>
      </h6>
        <ul class="nav flex-column mx-4">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="/questionnaire/dashboard/">
              <i class="fa fa-home"></i><span> Nyumbani</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="/questionnaire/submit-form/">
              <i class="fa fa-file-text"></i><span> Fomu Za Maelezo</span>
            </a>
          </li>
        </ul>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4  mx-2 mb-1 text-muted">
          <span>Taarifa na Ripoti</span>
        </h6>
        <ul class="nav flex-column mx-3 mb-2">
          <li class="nav-item">
            <a class="nav-link" href="/prediction/report/">
              <i class="fa fa-file-pdf-o"></i><span> Cheti</span>
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-12 ms-sm-auto col-lg-10 px-md-4">    
      {% comment %} <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 ">  {% endcomment %}
 
      {% block content%} 
      
      {% include 'prediction/form.html' %}
      
      {% endblock %}
    </main>
  </div>
</div>

</body>
</html>

AutomatedVerbalAutopsy/questionnaire/templates/questionnaire/permission_denied.html
<p>This functionnality is restricted</p>

AutomatedVerbalAutopsy/questionnaire/templates/questionnaire/profile.html
{% extends 'questionnaire/main.html'%}
{% block content %}
<div class="row mt-5 ">
    <div class="col-md-5">
        <div class="box box-default box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">My Profile</h3>
                <div class="box-tools d-flex justify-content-end">  
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body ">
                <table class="table table-bordered table-hover">
                     <tr>
                        <th>Full Name</th>
                        <td>{{first_name}} {{last_name}}</td>
                    </tr>
                    <tr>
                        <th>User Name</th>
                        <td>{{username}}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>{{email}}</td>
                </table>
            </div>

            <div class="box-footer">
                <a href="{% url 'questionnaire:update_profile' %}" class="btn btn-primary pull-right" >Update Profile</a>
            </div>

        </div>
    </div>
</div>
{% endblock  %}

AutomatedVerbalAutopsy/questionnaire/templates/questionnaire/register.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>CODM</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">

    

    <!-- Bootstrap core CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'questionnaire/css/boostrap_min.css' %}">
  
    

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">

{% load static %}
<link rel="stylesheet" href="{% static 'questionnaire/css/style.css' %}">
   

    
    <!-- Custom styles for this template -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'questionnaire/css/signin.css' %}">
    
  </head>
  <body class="text-center">
  <main class="form-signin">
  
  <form method="POST">
{% csrf_token %}
{% block content %}


{% endblock %}
  </form>

</main>
</body>
</html>

AutomatedVerbalAutopsy/questionnaire/templates/questionnaire/report.html
{% extends 'questionnaire/main.html'%}
{% block content %}
    {% if user.is_authenticated %}
     <div class="cotainer-centre mt-5">
      <table  class="table  table-striped table-hover">
        <h4 class="text-center mb-3"><b>Taarifa Zilizokusanywa</b></h4>
            <thead>
                <tr>
                    <th>No:</th>
                    <th>Marehemu</th>
                    <th>Jinsia</th>
                    <th>Kifo</th>
                    <th>Ushahidi</th>
                    <th>Sababu</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for marehemu in combined_data.marehemu_values %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ marehemu.jina_kwanza }} {{ marehemu.jina_pili }} {{ marehemu.jina_mwisho }}</td>
                    <td>{{ marehemu.jinsia }}</td>
                    <td>{{ marehemu.kufa }}</td>
                    <td>{{ marehemu.maelezo }}</td>
                    <td>
                        {% for sababu in combined_data.sababu_values %}
                            {% if sababu.Marehemu == marehemu %}
                                {{ sababu.sababu }}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        <a href="{% url 'prediction:download_report' marehemu.id %}" class="btn btn-primary">Pakua Cheti</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            
            <div class="pagination">
                <span class="step-links">
                    {% if combined_data.marehemu_values.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ combined_data.marehemu_values.previous_page_number }}">previous</a>
                    {% endif %}
            
                    <span class="current-page">{{ combined_data.marehemu_values.number }}</span>
            
                    {% if combined_data.marehemu_values.has_next %}
                        <a href="?page={{ combined_data.marehemu_values.next_page_number }}">next</a>
                        <a href="?page={{ combined_data.marehemu_values.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </table>            
    
        {% else %}
        <p>Please log in to access this page.</p>
       
    {% endif %}
        
    
{% endblock %}

AutomatedVerbalAutopsy/questionnaire/templates/questionnaire/update_profile.html
{% extends 'questionnaire/main.html'%}
{% block content %}
<div class="row mt-5 ">
    
    <div class="col-md-5">
        <div class="box box-default box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">My Profile</h3>
                <div class="box-tools d-flex justify-content-end">  
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body ">
                <form method="post" action="{% url 'questionnaire:Updated_profile' %}">
                    {% csrf_token %}
                    
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>Full Name</th>
                        <td><input type="text" name="username" value="{{ first_name }} {{ last_name }}"></td>
                    </tr>
                     <tr>
                        <th>User Name</th>
                        <td><input type="text" name="username" value="{{ username }}"></td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td><input type="email" name="email" value="{{ email }}"></td>
                </table>
            </div>

            <tr>
                <td colspan="2">
                    <button  class="btn btn-primary" type="submit">Save</button>
                </td>
            </form>
        </div>
    </div>
</div>
{% endblock %}