AutomatedVerbalAutopsy/AutomatedVerbalAutopsy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('member.urls')),
    path('questionnaire/', include('questionnaire.urls')),
    path('prediction/', include('prediction.urls')),
    path('admin/', admin.site.urls),
]

AutomatedVerbalAutopsy/member/urls.py
from. views import LoginView,LogoutView,RegisterView
from django.urls import path
from .views import changePassword,forgetPassword,password_reset_view
from django.views.decorators.csrf import csrf_exempt

app_name = 'member'

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('register', RegisterView.as_view(), name='register'),
    path('register/<str:message>/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('forget_password/', password_reset_view, name='forget_password'),
    path('change_password/<token>/', changePassword, name='change-password'),
]

AutomatedVerbalAutopsy/prediction/urls.py
from django.urls import path
from . import views

app_name = 'prediction'

urlpatterns = [
    path('predict/', views.predict_disease, name='predict'),
    path('success/', views.success, name='success'),
    path('badili/', views.delete_questionnaire, name='badili'),
    path('download/<int:marehemu_id>/', views.download_report, name='download_report'),
    path('report/', views.report, name='report'),    
]

AutomatedVerbalAutopsy/prediction/models.py
from django.db import models

AutomatedVerbalAutopsy/prediction/forms.py
from django import forms

class PredictionForm(forms.Form):
    # jina_kwanza = forms.CharField(max_length=100)
    # jina_pili = forms.CharField(max_length=100, required=False)
    # jina_mwisho = forms.CharField(max_length=100)
    # jinsia = forms.ChoiceField(choices=[('M', 'Mwanamume'), ('F', 'Mwanamke')])
    # ndoa = forms.BooleanField(required=False)
    # kuzaliwa = forms.DateField()
    # kufa = forms.DateField()
    # mahali = forms.CharField(max_length=100)
    # maelezo = forms.CharField(widget=forms.Textarea)
    sababu = forms.CharField(widget=forms.HiddenInput())

AutomatedVerbalAutopsy/prediction/views.py
from django.contrib import messages,auth
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
import pickle
import os
from django.contrib.auth.decorators import login_required
from django.templatetags.static import static
from django.core.paginator import Paginator
from django.http import HttpResponseBadRequest
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn import metrics
import pandas as pd
from django.http import HttpResponse
from django.template.loader import get_template
from .forms import PredictionForm
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from questionnaire.models import Shuhuda,Marehemu,Sababu
from django.http import FileResponse
import io
from django.utils import timezone
from reportlab.lib.units import inch

MODELFILE = settings.MODEL_DIR + '/naive_bayes.pkl'
VECFILE = settings.MODEL_DIR + '/count_vectorizer.pkl'


with open(MODELFILE, 'rb') as f:
    model = pickle.load(f)

with open(VECFILE, 'rb') as f:
    vectorizer = pickle.load(f)  


@login_required
def delete_questionnaire(request):
    username = request.user.username
    marehemu_to_delete = Marehemu.objects.latest('id')
    sababu_to_delete = marehemu_to_delete.sababu

    if request.method == 'POST':
        sababu_to_delete.delete()
        marehemu_to_delete.delete()
        return redirect('questionnaire:submit_form')

    context = {
        'object_to_delete': marehemu_to_delete,
        'username': username
    }
    return render(request, 'prediction/success.html', context)


@login_required
def predict_disease(request):
    username = request.user.username
    inputs =Marehemu.objects.order_by('-id').values_list('maelezo', flat=True).first()
    other_field= Marehemu.objects.all().order_by('-id').first()
    if isinstance(inputs, str):
        inputs = [inputs]
    user_input_vector = vectorizer.transform(inputs)
    prediction = model.predict(user_input_vector)[0]
    disease_scores = model.predict_proba(user_input_vector)[0]
    scores_percentage = [round(score * 100, 2) for score in disease_scores]
    inputs = str(inputs[0]) 
    marehemu_instance = get_object_or_404(Marehemu, id=other_field.id)
    sababu, created = Sababu.objects.get_or_create(
        Marehemu=marehemu_instance,
        defaults={'sababu': prediction}
    )
    context = {
        'prediction': prediction,
        'diseases_scores': zip(model.classes_, scores_percentage),
        'all_maelezo': inputs,
        'username':username,
        'other_field':other_field
        }

    return render(request, 'prediction/success.html', context, )


@login_required
def success(request, message=None):
    username = request.user.username 
    cod_with_sababu_data = Sababu.objects.all()
    context = {
        'cod_with_sababu_data': cod_with_sababu_data,
        'username':username
    }
    return render(request, 'questionnaire/report.html', context)




@login_required
def report(request):
    sababu_values = Sababu.objects.all().order_by('-id')
    marehemu_values = []
    shuhuda_values = []

    for sababu in sababu_values:
        marehemu = sababu.Marehemu 
        marehemu_values.append(marehemu)
        shuhuda_values.append(marehemu.shuhuda.all())

    search_query = request.GET.get('query')
    if search_query:
        marehemu_values = Marehemu.objects.filter(jina_kwanza__icontains=search_query)


    combined_data = {
        'sababu_values': sababu_values,
        'marehemu_values': marehemu_values,
        'shuhuda_values': shuhuda_values
    }

    return render(request, 'questionnaire/report.html', {'combined_data': combined_data})



@login_required
def download_report(request, marehemu_id): 
    current_date = timezone.now().date()
    marehemu = get_object_or_404(Marehemu, id=marehemu_id)
    shuhuda= get_object_or_404(Shuhuda ,id=marehemu_id)

    response = HttpResponse(content_type='application/pdf')

    response['Content-Disposition'] = 'attachment; filename="death_certificate.pdf"'

    p = canvas.Canvas(response)

    p.setFont("Helvetica", 12)
    p.drawString(200, 800, "University Of Dar-es-Salaam")
    p.drawString(150, 780, "Collage of Information and Communication Technology")
    p.drawString(200, 760, "Cause of Death Manipulation")
    p.drawString(180, 740, "-------------------------------------------------")
    p.drawString(220, 700, "DEATH CERTIFICATE")
    p.drawString(30, 670, "This is to verify that the following information has been obtained from the verbal autopsy of the deceased ")
    p.drawString(20, 650, f"registered under caretaker,{shuhuda.first_name} {shuhuda.middle_name} {shuhuda.last_name} with corresponds deceased's information below.")
    p.drawString(20, 620, f"Full Name: {marehemu.jina_kwanza} {marehemu.jina_pili} {marehemu.jina_mwisho} ")
    p.drawString(250, 620, f"Place of Death: {shuhuda.place}, {shuhuda.region}")
    p.drawString(20, 600, f"Sex: {marehemu.jinsia}")
    p.drawString(250, 600, f"Date of Birth: {marehemu.kuzaliwa}")
    p.drawString(20, 580, f"Date of Death: {marehemu.kufa}")
    p.drawString(250, 580, f"Place of Death: {marehemu.mahali}")
    p.drawString(20, 560, f"Cause of Death: {marehemu.sababu.sababu}")
    p.drawString(20, 520, f"Date: {current_date}")
    p.drawString(250, 520, "Signature ............")
    
    p.showPage()
    p.save()

    return response

AutomatedVerbalAutopsy/prediction/templates/prediction/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Make a Prediction</title>
</head>
<body>
	<h1>Make a Prediction</h1>
	<form method="POST" action="{% url 'prediction:index' %}">
		{% csrf_token %}
			<label for="inputs">Input:</label>
			<input type="text" name="inputs" id="inputs" required>
		<button type="submit">Predict</button>
	</form>
	{% if prediction %}
		<p>Prediction: {{ prediction }}</p>
	{% endif %}
</body>
</html>

AutomatedVerbalAutopsy/prediction/templates/prediction/main.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>CODM</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard/">

    

    <!-- Bootstrap core CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'prediction/css/boostrap_min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <!-- Include jQuery -->
    <script src="{% static 'prediction/static/js/jquery.min.js' %}"></script>
    <!-- Include Bootstrap JS -->
    <script src="{% static 'prediction/static/js/bootstrap.min.js' %}"></script>



    <!-- Favicons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


     {% load static %}
     <link rel="stylesheet" href="{% static 'prediction/css/style.css' %}">

  

    
    <!-- Custom styles for this template -->
    {% load static %}
<link rel="stylesheet" href="{% static 'prediction/css/main.css' %}">


  </head>
  <body>
    
<header class="navbar navbar-success sticky-top flex-md-nowrap p-0 shadow back">
    <div class="navbar-nav ">
      <div class="nav-item  text-nowrap">
        <a class="nav-link text-light px-3" href="#"><u> </u></a>
      </div>
    </div>
    <div class="navbar-nav text-decoration-none p-2" >
       <div class="nav-item  text-nowrap">
        {% if username %}
        <div class="row">
          <div class="col-sm-6">
        <a class="nav-link text-light  fs-5 px-3" href="#"><i class="fas fa-user-circle"></i>  {{ username }}</a>
      </div>
        <div class="col-sm-6">
          <a  class="nav-link  text-light fs-5 " href="{% url 'member:logout' %}"><u>Sign Out</u></a>
        </div>
      </div>
       {% endif %}
      </div>
    </div>
    
</header>

<div class="container-fluid">
  <div class="row ">
    {% load static %}
   
  </div>
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <div class="m-3 mb-5">
        <img src="{% static 'prediction/images/logo.png' %}" alt="Logo" style="width:150px; height:150px;">
      </div>
        <ul class="nav flex-column mx-4">
          <li class="nav-item">
            <a class="nav-link " aria-current="page" href="/Questionnaire/dashboard/">
              <span data-feather="Home.html"></span>
              Nyumbani
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/Questionnaire/submit-form/">
              <span data-feather="form.html"></span>
              Fomu Za Maelezo
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/report/">
              <span data-feather="shopping-cart"></span>
              Ripoti
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4  mx-2 mb-1 text-muted">
          <span>Taarifa na Ripoti</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mx-3 mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Mwezi Huu
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
<!--     
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 "> -->
 
      {% block content%} 
      
      
      
      {% endblock %}
    </main>
  </div>
</div>

</body>
</html>

AutomatedVerbalAutopsy/prediction/templates/prediction/report.html
{% extends 'questionnaire/main.html'%}
{% block content %}
    <ul>
        <p>{{ pdf_content }}</p>
        
{% endblock %}

AutomatedVerbalAutopsy/prediction/templates/prediction/success.html
{% extends 'questionnaire/main.html'%}
{% block content %}
<div class="row">
    <div class="cotainer-centre mt-5">
        <table  class="table  table-striped">
            <h4 class="text-center mb-3"><b>Taariza Za Marehemu</b></h4>
              <thead>
                <tr>
                  <th>Jina la Marehemu</th>
                  <th>Jinsia</th>
                  <th>Ndoa</th>
                  <th>Kuzaliwa</th>
                  <th>Kufa</th>
                  <th>Mahali</th>
                  <th>Maelezo</th>
                  <th>Sababu</th>
                  <th>Zinginezo</th>
                </tr>
            </thead>
            <tbody>
              <tr>
                <td >{{ other_field.jina_kwanza }} {{ other_field.jina_pili }} {{ other_field.jina_mwisho }}</td>
                <td >{{ other_field.jinsia }} </td>
                <td >{{ other_field.ndoa }} </td>
                <td >{{ other_field.kuzaliwa }} </td>
                <td > {{ other_field.kufa }} </td>
                <td > {{ other_field.mahali }} </td>
                <td > {{ other_field.maelezo }} </td>
                <td>
                  {% if prediction %}
                    {{ prediction }}
                 
                    <input type="hidden" name="sababu" value="{{ prediction }}">
                </td>
                <td>
                {% for disease, score in diseases_scores %}
                <li>{{ disease }}: {{ score }}%</li>
            {% endfor %}
            {% endif %}
              </td>
              </tr>
            </tbody>
        </table>
      </div>   
    </div>  

<div class="row">
  <div class="col-md-3">
    <form name="questionnaire" action="{% url 'prediction:badili' %}" method="POST" >
       {% csrf_token %}
      <button class="btn btn-secondary">Rudia</button>
    </form>
  </div>
  <div class="col-md-7"> </div>
  <div class="col-md-2">
    <form name="questionnaire" action="{% url 'prediction:report' %}" method="POST" >
      {% csrf_token %}
    <button  class="btn btn-primary">wasilisha</button>
  </form>
  </div>
</div>
{% endblock %}

AutomatedVerbalAutopsy/prediction/templates/prediction/success1.html
{% extends 'questionnaire/main.html'%}
{% block content %}
    <p>You have successful insert the data</p>
    <ul>
        {% for cod_with_sababu_obj in cod_with_sababu_data %}
          <li>Jina Kwanza: {{ cod_with_sababu_obj.jina_kwanza }}</li>
          <li>Sababu: {{ cod_with_sababu_obj.sababu }}</li>
          <ul>
            {% for cod_obj in cod_with_sababu_obj.cod_ptr.all %}
              <li>Jina Kwanza: {{ cod_obj.jina_kwanza }}</li>
              <!-- Display other fields of COD model as needed -->
            {% endfor %}
          </ul>
        {% endfor %}
      </ul>
{% endblock %}